<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Trirong">

    <link rel="stylesheet" type="text/css" href="payscript.css">
    <script type="text/javascript" src="f_script.js"></script>

    <title>Donate</title>
  </head>
  <body>
    <!---------------NAVBAR------------------->
      <nav class="topnav">
        <img src="images/logo.jpg" alt="logo" id="logo">
        <div class="tabs">
        <a href="#contact" id="tabs">Contact</a>
        </div>
      </nav> 
     

     <!---------------RAZORPAY------------->
     <?php

        $apiKey = "rzp_live_QwQpD2z8a9Cekq";

        ?>

        <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
        <center>
        <form action=" " method="POST" id="pay">
            <script    
                src="https://checkout.razorpay.com/v1/checkout.js"    
                data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys   
                data-amount='100' // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account    
                data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.    
                data-buttontext="Pay with Razorpay"    
                data-name="The Smile Foundation"    
                data-description="Donate for happier childhoods"    
                data-image="https://t4.ftcdn.net/jpg/03/35/95/47/360_F_335954772_DXpPAtzlHmqlgPkWi0oRXE33D0QYZHKd.jpg"    
                data-prefill.name="<?php echo $_POST['name'];?>"    
                data-prefill.contact="<?php echo $_POST['contact'];?>"  
                data-prefill.email="<?php echo $_POST['email'];?>"  
                data-theme.color="#182b66"></script>
            <input type="hidden" custom="Hidden Element" name="hidden">
        </form></center>


    <!---------FOOTER----------->
   <footer class="footer" id="contact">
     <div class="footer-container">
      <div class="row">
        <div class="footer-col">
          <h4>OFFICE ADDRESS</h4>
          <ul>
            <li><a>Lorem Ipsum dolor, 234
              1200 Consecteur
              Adipiscing</a></li>
          </ul>
        </div>
        
        <div class="footer-col">
          <h4>CONTACT US</h4>
          <ul>
            <li><a >+123 456 789</a></li>
            <li><a >smile@skype</a></li>
            <li><a >enquiry@smile.com</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>FOLLOW US</h4>
          <div class="social-links">
            <img id="logo-1" src="images/fb.jpg">
            <img id="logo-2" src="images/ig.jpg">
            <img id="logo-2" src="images/twitter-logo.jpg">
          </div>
        </div>
      </div>
     </div>
  </footer>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>
